#!/usr/bin/env bash

set -e

command="$1"
basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Functions
missing_command() {
  echo "Usage: e [command] [...args]"
  echo "Please provide a valid command: 'bootstrap', 'build', 'debug', 'export-patches', 'get', 'pr', 'start', 'sync', 'test', or 'testnode'."
  exit 1
}

run_command() {
  cmd="$1"
  shift
  script_path="$basedir/commands/$cmd.sh"
  if [ ! -f "$script_path" ]; then
    echo Invalid Command: \""$cmd"\"
    echo ""
    missing_command
  else
    "$script_path" "$@"
  fi
}

shift
run_command "$command" "$@"
