#!/usr/bin/env bash

set -e

# Functions
usage() {
  echo -e "Usage:

  e {command} [-h | --help]

Commands:

  fetch           All-in-one tool for setting up GN + \`e sync\` + \`e bootstrap\`
  sync            Fetch source / synchronize repository checkouts
  bootstrap       Generate build commands
  build           Build electron

  start           Run Electron
  node            Run Electron as Node
  debug           Run Electron in a debugger
  test            Run Electron's spec runner
  testnode        Run Electron's node spec runner

  export-patches  Geneate patches from a development branch
  pr              Submit a pull request

  show            Query the build-tools config
"
}

readonly cmd="$1"
readonly basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [[ "$cmd" = '-h' || "$cmd" = '--help' ]]; then
  usage
  exit 0
elif [[ "$cmd" = '' || ! -f "$basedir/commands/$cmd.sh" ]]; then
  echo "Unrecognized command: \"$cmd\". See \`e --help\` for usage information."
  exit 1
else
  shift
  "$basedir/commands/$cmd.sh" "$@"
fi
