#!/usr/bin/env bash

set -e

readonly basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Functions
usage() {
  echo -n 'Usage: e {'
  local -r -a scripts=($basedir/commands/[a-z]*\.sh)
  local -r n=${#scripts[@]}
  for i in "${!scripts[@]}"; do
    echo -n "$(basename -s '.sh' "${scripts[$i]}")"
    if (( $i+1 < $n )); then
      echo -n ' | '
    fi
  done
  echo '} [...args]'
  exit 1
}

run_command() {
  local -r cmd="$1"
  shift
  local -r script_path="$basedir/commands/$cmd.sh"
  if [[ ! -f "$script_path" ]]; then
    echo Invalid Command: \""$cmd"\"
    echo ""
    usage
  else
    "$script_path" "$@"
  fi
}

if (( $# == 0 )); then
  usage
else
  run_command "$@"
fi

