#!/usr/bin/env node

const fs = require('fs');
const loadConfig = require('./load-config');
const util = require('./util')

const usage = () => {
  console.log(
`Usage:
  edit-evm-config configName [--key=val]... [key val]...

Options
  --help, -h   Display this help message
  --key=val    Add or change an evm config file property
  key val      Add or change an evm config file property

Examples:
  edit-evm-config master --buildType=debug`);
}

if (process.argv.includes('-h') || process.argv.includes('--help')) {
  usage();
  process.exit(0);
}
if (process.argv.length < 3) { // first two are 'node', 'scriptname'
  console.error('Missing arguments. See `edit-evm-config --help` for usage information.');
  process.exit(1);
}

const configName = process.argv[2];
const configFile = util.getConfigFile(configName);
const config = loadConfig(configFile);

for (let i=3; i<process.argv.length; ) {
  let key = process.argv[i];

  if (key.startsWith('--') && key.includes('=')) {
    const pos = key.indexOf('=');
    const val = key.slice(pos+1);
    key = key.slice(2, pos);
    config[key] = val;
    i += 1;
  }
  else if (i+1 < process.argv.length) {
    const val = process.argv[i+1];
    config[key] = val;
    i += 2;
  }
  else {
    console.error(`Unrecognized argument '${arg}'`);
    process.exit(1);
  }
}

util.saveConfig(configFile, config);
console.log(`Saved "${configFile}"`);
