name: Validate Configs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-config:
    name: Validate Configs
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Validate JSON schema
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          schema: json-schema
          files: evm-config.schema.json
      - name: Validate GitHub Actions workflows
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/*.yml
      - name: Validate .prettierrc.json
        uses: dsanders11/json-schema-validate-action@f04ef3bca791388d2bd9ff3a50b27d1b2572158e # v2.1.0
        with:
          schema: https://json.schemastore.org/prettierrc.json
          files: .prettierrc.json
