name: Validate Configs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-config:
    name: Validate Configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Validate JSON schema
        uses: dsanders11/json-schema-validate-action@80a355077d1e23287030ac8abb7e01dc46c10d89 # v1.1.2
        with:
          schema: json-schema
          files: evm-config.schema.json
      - name: Validate GitHub Actions workflows
        uses: dsanders11/json-schema-validate-action@80a355077d1e23287030ac8abb7e01dc46c10d89 # v1.1.2
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/*.yml
      - name: Validate .prettierrc.json
        uses: dsanders11/json-schema-validate-action@80a355077d1e23287030ac8abb7e01dc46c10d89 # v1.1.2
        with:
          schema: https://json.schemastore.org/prettierrc.json
          files: .prettierrc.json
