name: Validate Configs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-config:
    name: Validate Configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate JSON schema
        uses: dsanders11/json-schema-validate-action@79b2d95a446a0d786f7f244ae7764f8370ff3657 # v1.4.0
        with:
          schema: json-schema
          files: evm-config.schema.json
      - name: Validate GitHub Actions workflows
        uses: dsanders11/json-schema-validate-action@79b2d95a446a0d786f7f244ae7764f8370ff3657 # v1.4.0
        with:
          schema: https://json.schemastore.org/github-workflow.json
          files: .github/workflows/*.yml
      - name: Validate .prettierrc.json
        uses: dsanders11/json-schema-validate-action@79b2d95a446a0d786f7f244ae7764f8370ff3657 # v1.4.0
        with:
          schema: https://json.schemastore.org/prettierrc.json
          files: .prettierrc.json
